# Generated by Django 3.2.13 on 2022-05-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=30)),
                ('author', models.CharField(default='', max_length=30)),
                ('content', models.TextField(default='', max_length=200)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
