# Generated by Django 3.2.13 on 2022-05-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_comments', '0004_blogcomment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='likes',
        ),
    ]
