# Generated by Django 3.2.13 on 2022-05-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_comments', '0006_blogcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='post_comments.blogcomment'),
        ),
    ]
