# Generated by Django 3.2.13 on 2022-05-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_comments', '0013_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
    ]
